### ISSUE TITLE
On the hosted agent detect Chrome automatically

### ISSUE THREAD

**Issue by jessehouwing** [geeklearningio/gl-vsts-tasks-ghost#1]
On the hosted agent Chrome is installed here:

     c:\program files (x86)\google\chrome\Application\chrome.exe

The task runs great then I add a variable `chromium.bin` with the value above.

It would be great if the task would probe this registry key:

    HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe 

This would prevent the slow Chromium task.

![image](https://user-images.githubusercontent.com/4173387/42214529-152e7d10-7ebc-11e8-98b8-f2f5ce3032dc.png)

**Comment by sandorfr** [comment]
Just pushed an update to address that. Also screenshots are automatically attached to the build.
