### ISSUE TITLE
blogged about it

### ISSUE THREAD

**Issue by jessehouwing** [geeklearningio/gl-vsts-tasks-ghost#10]
https://jessehouwing.net/ghost-vsts-continuous-delivery-of-customized-themes/

**Comment by jessehouwing** [comment]
Dude/mate/mister/sir all works. Thanks for building the task :).

**Comment by sandorfr** [comment]
Hi @jessehouwing,

Just published the 1.0.0. It is mostly minor improvments however, it now uses a dedicated endpoint type instead of the `generic` type. 

That's a breaking changes so you may want to update your blog post :)

Cheers,
Cyprien
