### ISSUE TITLE
When chromium isn't installed, the task succeeds

### ISSUE THREAD

**Issue by jessehouwing** [geeklearningio/gl-vsts-tasks-ghost#8]
BUG

When chromium isn't found, the Ui automation library writes an error to the log. The error isn't detected by the agent and the task succeeds as well as the build that contains the task.

Expected behavior:

* [ ] The error message which is written when chromium isn't found is logged as a true error to the agent.
* [ ] The task is marked as failed

**Comment by sandorfr** [comment]
Fixed in 1.0
